### ISSUE TITLE
[DTL] - GCC i Clang nie kompilują projektu

### ISSUE THREAD

**Issue by GoscZnickiem** [igorjakus/minigolf#1]
GCC i Clang nie rozpoznają konstrukcji makra DTL_ERR o pojedynczym argumencie z biblioteki DTL (Zapewne nie rozpoznają też poprawnie innych makr z tej biblioteki).

![obraz_2023-12-12_154903583](https://github.com/igorjakus/minigolf/assets/33461512/1e6d5fbc-9e7f-4048-a862-40ec526079ec)

Błąd powoduje przerwanie kompilacji **co uniemożliwia zbudowanie aplikacji na systemach Linux i MacOS**.

MSVC kompiluje ten program prawidłowo ponieważ wspiera "trailing comma":

![image](https://github.com/igorjakus/minigolf/assets/33461512/e5a7d66b-dbaf-48bd-bc6e-b0e8fd4dac11)

**Comment by frogrammer9** [comment]
Naprawiłem 👍
