### ISSUE TITLE
GLFW nie inicjalizuje się na Linuxie (Debianie)

### ISSUE THREAD

**Issue by GoscZnickiem** [igorjakus/minigolf#12]
No to właściwie tyle. Od "naprawienia" issue #5 GLFW nie inicjalizuje się na linuxie.

Error log:
[00:00:00][ERR] Failed to initialize GLFW

Propozycja jest taka: skoro na MacOS i tak GLFW nie działa to proponuje zrevertować zmiany z "naprawienia" issue #5

**Comment by igorjakus** [comment]
Zamykam bo już @GoscZnickiem zrevertował zmiany.
