### ISSUE TITLE
GLFW nie działa na Linux

### ISSUE THREAD

**Issue by GoscZnickiem** [igorjakus/minigolf#2]
Program kompiluje się i uruchamia na Linuxie jednak GLFW nie może zostać zainicjalizowane

**Comment by frogrammer9** [comment]
Zmieniłem plik zawierający bibliotekę GLFW na odpowiednik pobrany z oficjalnego github-a glfw. Obecnie może być ona niezoptymalizowana pod potrzeby tego projektu ale z moich testów wynika, że teraz program uruchamia się prawidłowo.

**Comment by GoscZnickiem** [comment]
Bobam
