### ISSUE TITLE
Nie kompiluje sie na MacOS

### ISSUE THREAD

**Issue by igorjakus** [igorjakus/minigolf#5]
Wklejam pierwszego errora co wyskoczył

igorjakus@MacBook-Air-Igor unixlike-gcc-debug % ninja
[4/33] Building C object src/AGL-Deps/.../CMakeFiles/glfw.dir/cocoa_monitor.m.o

FAILED: src/AGL-Deps/GLFW/src/CMakeFiles/glfw.dir/cocoa_monitor.m.o 
/usr/bin/gcc -DGLM_FORCE_CXX11 -DGLM_FORCE_SILENT_WARNINGS -D_GLFW_USE_CONFIG_H -D__COMPILER_GCC__ -D__DEBUG__ -I/Users/igorjakus/projects/minigolf/src -I/Users/igorjakus/projects/minigolf/src/AGL-Deps/GLFW/include -I/Users/igorjakus/projects/minigolf/src/AGL-Deps/GLFW/src -I/Users/igorjakus/projects/minigolf/build/unixlike-gcc-debug/src/AGL-Deps/GLFW/src -x c -g -std=gnu99 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.5 -fPIC -Wall -MD -MT src/AGL-Deps/GLFW/src/CMakeFiles/glfw.dir/cocoa_monitor.m.o -MF src/AGL-Deps/GLFW/src/CMakeFiles/glfw.dir/cocoa_monitor.m.o.d -o src/AGL-Deps/GLFW/src/CMakeFiles/glfw.dir/cocoa_monitor.m.o -c /Users/igorjakus/projects/minigolf/src/AGL-Deps/GLFW/src/cocoa_monitor.m

Pzdr

**Comment by GoscZnickiem** [comment]
wysłałeś dosłownie tylko który plik się nie skompilował

**Comment by igorjakus** [comment]
> wysłałeś dosłownie tylko który plik się nie skompilował

wolisz to, czy caly referat od wojownika ninja?

**Comment by GoscZnickiem** [comment]
Wolę żeby Łukasz się do tego dołączył bo on będzie prędzej wiedział o co chodzi xD

Jak nic nie wyjdzie to nie wiem może dodam GLFW w poprzedniej wersji specjalnie na Maca.

**Comment by frogrammer9** [comment]
I've fixed the problem with not working GLFW on MacOS however out program requires OpenGL 4.6 and since MacOS canceled support for OpenGL with version 4.1 i don't guarantee it will work. I don't plan doing anythin about it for now.

**Comment by GoscZnickiem** [comment]
Brat co polskiego zapomniał. Czego właściwie używasz z GL 4.6?
