### ISSUE TITLE
Błąd kompilacji z MSVC (Windows)

### ISSUE THREAD

**Issue by igorjakus** [igorjakus/minigolf#6]
Błąd przy ustawionej konfiguracji msvc Debug, o dziwo z clang Debug działa xD

>------ Kompiluj wszystko — uruchomiono: projekt: minigolf, konfiguracja: msvc-debug ------
  [1/3] Copy assets folder to executable
  [2/3] Building CXX object src\App\CMakeFiles\mini_golf.dir\ECS\Component.cpp.obj
  FAILED: src/App/CMakeFiles/mini_golf.dir/ECS/Component.cpp.obj 
  C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe  /nologo /TP -DGLM_FORCE_CXX11 -DGLM_FORCE_SILENT_WARNINGS -DSAMPLE_LIBRARY_STATIC_DEFINE -D__COMPILER_CL__ -D__DEBUG__ -IC:\Users\igorj\source\repos\minigolf\src -IC:\Users\igorj\source\repos\minigolf\src\AGL-Deps -IC:\Users\igorj\source\repos\minigolf\src\AGL-Deps\GLFW\include -IC:\Users\igorj\source\repos\minigolf\src\AGL-Deps\GLAD\include -IC:\Users\igorj\source\repos\minigolf\src\pch -IC:\Users\igorj\source\repos\minigolf\src\Util -IC:\Users\igorj\source\repos\minigolf\src\AGL-Deps\glm\.. -IC:\Users\igorj\source\repos\minigolf\src\AGL-Deps\stb -IC:\Users\igorj\source\repos\minigolf\src\AGL -IC:\Users\igorj\source\repos\minigolf\src\DTL -IC:\Users\igorj\source\repos\minigolf\src\AGL-Deps\ImGui /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -std:c++20 -MDd /W4 /w14242 /w14254 /w14263 /w14265 /w14287 /we4289 /w14296 /w14311 /w14545 /w14546 /w14547 /w14549 /w14555 /w14619 /w14640 /w14826 /w14905 /w14906 /w14928 /permissive- /WX /YuC:/Users/igorj/source/repos/minigolf/build/msvc-debug/src/App/CMakeFiles/mini_golf.dir/cmake_pch.hxx /FpC:/Users/igorj/source/repos/minigolf/build/msvc-debug/src/App/CMakeFiles/mini_golf.dir/./cmake_pch.cxx.pch /FIC:/Users/igorj/source/repos/minigolf/build/msvc-debug/src/App/CMakeFiles/mini_golf.dir/cmake_pch.hxx /showIncludes /Fosrc\App\CMakeFiles\mini_golf.dir\ECS\Component.cpp.obj /Fdsrc\App\CMakeFiles\mini_golf.dir\ /FS -c C:\Users\igorj\source\repos\minigolf\src\App\ECS\Component.cpp
C:\Users\igorj\source\repos\minigolf\src\App\ECS\Component.cpp(39): error C2220: następujące ostrzeżenie jest traktowane jako błąd
C:\Users\igorj\source\repos\minigolf\src\App\ECS\Component.cpp(39): warning C4702: kod nieosiągalny
  ninja: build stopped: subcommand failed.

Kompiluj wszystko — niepowodzenie.

**Comment by GoscZnickiem** [comment]
Tak to znany (i niezwykle dziwny) problem. Kompilator z blizej nieznanych mi przyczyn najpierw wyklucza kod znajdujący się w IFNDEFie a potem próbuje się do niego dostać bo __Dist__ przecież nie jest zadeklarowany. Tymczasowe rozwiazanie jest takie żeby:
a) usunąć dyrektywy preprocessora w tym miejscu
b) nie budować projektu na msvc-debug/relwithdebinfo (ten kompilator i tak jest useless tbh)

**Comment by igorjakus** [comment]
> Tak to znany (i niezwykle dziwny) problem. Kompilator z blizej nieznanych mi przyczyn najpierw wyklucza kod znajdujący się w IFNDEFie a potem próbuje się do niego dostać bo **Dist** przecież nie jest zadeklarowany. Tymczasowe rozwiazanie jest takie żeby: a) usunąć dyrektywy preprocessora w tym miejscu b) nie budować projektu na msvc-debug/relwithdebinfo (ten kompilator i tak jest useless tbh)

albo calkiem usunac msvc, bo czemu nie
