### ISSUE TITLE
GUI elements dont work when the camera position isn't 0, 0

### ISSUE THREAD

**Issue by frogrammer9** [igorjakus/minigolf#8]
It look like the collision detection doesn't take into consideration the camera position offset.

**Comment by GoscZnickiem** [comment]
Czego po angielsku piszez, języka ojczystego zapomniałeś? Ale tak, offset kamery nie powinien być brany pod uwagę bo kamera warstwy gui powinna permamentnie mieć pozycje (0, 0). Jeśli napotkałeś jakieś dziwne zachowania to pewnie dlatego że patrzyłeś na starą wersję GUI gdzie popełniłem taki dość głupi błąd... dodawałem komponenty wizualne do świata gry zamiast warstwy gui xD
