### ISSUE TITLE
Someone should test if the new audio API works correctly on Linux and Mac since I've only tested on Windows.

### ISSUE THREAD

**Issue by frogrammer9** [igorjakus/minigolf#9]

**Comment by igorjakus** [comment]
Nie wiem jak mam sprawdzić jak się nie kompiluje na macu dalej... Trzeba nad tym usiąść bo lipa

**Comment by igorjakus** [comment]
Ogólnie sama biblioteka działa poza tym projektem, ale still nie sprawdzę w projekcie bo najpierw by trzeba było odłączyć renderowanie zanim skompiluje na macu.

**Comment by GoscZnickiem** [comment]
Kompiluje się (po dokonaniu małej poprawki żeby clang się nie czepiał o old-style casty). Pojawia się jednak problem z uruchomieniem programu na linuxie (a przynajmniej na moim debianie) - a dokładniej inicjalizacją GLFW.

**Comment by igorjakus** [comment]
Ogólnie działa ale jest problem z segfaultami na linuxie. Na windowsie dziala g, a wersje na Maca porzucamy bo AGL nie wspiera:|
